[BITS 16] ;SET TO 16-BIT MODE.
[ORG 0X7C00] ;SET ORIGIN.

_START:
    CLI ; CLEAR INTERRUPTS.
    MOV AX, 0X00
    MOV DS, AX
    MOV ES, AX
    MOV SS, AX
    MOV SP, 0X7C00 ;SET SP TO TOP OF BOOTLOADER SEGMENT.
    STI ; START INTERRUPTS.
    
PRINT:
    LODSB ;LOAD SP AND INCREMENT IT.
    CMP AL, 0 ;CHECK FOR NULL TERMINATOR.
    JE DONE ;JUMP TO DONE IF END OF STRING.
    MOV AH, 0X0E ;SET AH TO BIOS TELETYPE OUTPUT FUNCTION.
    INT 0X10 ;CALL BIOS INTERRUPT FOR TELETYPE OUTPUT.
    JMP PRINT ;JUMP TO PRINT TO PROCESS NEXT CHARACTER.

DONE:
    CLI ;CLEAR INTERRUPTS.
    HLT ;HALT CPU.
 
;GDT IMPLEMENTATION
GDT_START:
    DB 0X00000000
    DB 0X00000000

    ;CODE SEGMENT DESCRIPTOR.
    DW 0XFFFF    ;LIMIT.
    DW 0X0000    ;BASE.
    DB 0X00      ;BASE.
    DB 10011010b ;ACCESS BYTE.
    DB 11001111b ;FLAGS.
    DB 0x00	 ;BASE.

    ;DATA SEGMENT DESCRIPTOR.
    DW 0XFFFF    ;LIMIT.
    DW 0X0000    ;BASE.
    DB 0X00      ;BASE.
    DB 10010010b ;ACCESS BYTE.
    DB 11001111b ;FLAGS.
    DB 0x00	 ;BASE.

GDT_END:

GDT_DESCRIPTOR:
    DW GDT_END - GDT_START - 1 ;SIZE OF GDT-1.
    DD GDT_START ;BASE ADDRESS OF GDT.

TIMES 510 - ($ - $$) DB 0

DW 0XAA55
